server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_db_name?serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 60000
      connection-timeout: 30000
